"""Pydantic schemas package"""

from app.schemas.auth import Token, TokenData
from app.schemas.budget import (
    BudgetAlertCreate,
    BudgetAlertResponse,
    BudgetAlertUpdate,
    BudgetCreate,
    BudgetOverviewResponse,
    BudgetPeriodResponse,
    BudgetResponse,
    BudgetRolloverRequest,
    BudgetRolloverResponse,
    BudgetSummaryResponse,
    BudgetUpdate,
)
from app.schemas.debt import (
    DebtCreate,
    DebtPaymentCreate,
    DebtPaymentResponse,
    DebtPayoffProjection,
    DebtResponse,
    DebtSummary,
    DebtUpdate,
    InterestCalculatorRequest,
    InterestCalculatorResponse,
    PayoffPlanRequest,
    PayoffPlanResponse,
    PayoffStrategy,
)
from app.schemas.insight import (
    CashflowForecastResponse,
    DashboardInsightsResponse,
    GenerateForecastRequest,
    InsightFilterParams,
    PredictiveInsightCreate,
    PredictiveInsightResponse,
    PredictiveInsightUpdate,
    SpendingAnomalyResponse,
    SpendingForecastResponse,
)
from app.schemas.transaction import (
    CategoryCreate,
    CategoryResponse,
    CategoryUpdate,
    CSVImportRequest,
    CSVImportResponse,
    SpendingByCategoryResponse,
    SpendingTrendResponse,
    TransactionCreate,
    TransactionFilter,
    TransactionResponse,
    TransactionRuleCreate,
    TransactionRuleResponse,
    TransactionRuleUpdate,
    TransactionUpdate,
)
from app.schemas.user import User, UserCreate, UserInDB, UserUpdate

__all__ = [
    # Auth schemas
    "Token",
    "TokenData",
    # User schemas
    "User",
    "UserCreate",
    "UserInDB",
    "UserUpdate",
    # Budget schemas
    "BudgetCreate",
    "BudgetUpdate",
    "BudgetResponse",
    "BudgetAlertCreate",
    "BudgetAlertUpdate",
    "BudgetAlertResponse",
    "BudgetPeriodResponse",
    "BudgetSummaryResponse",
    "BudgetOverviewResponse",
    "BudgetRolloverRequest",
    "BudgetRolloverResponse",
    # Debt schemas
    "DebtCreate",
    "DebtUpdate",
    "DebtResponse",
    "DebtPaymentCreate",
    "DebtPaymentResponse",
    "DebtSummary",
    "PayoffStrategy",
    "PayoffPlanRequest",
    "PayoffPlanResponse",
    "DebtPayoffProjection",
    "InterestCalculatorRequest",
    "InterestCalculatorResponse",
    # Transaction schemas
    "CategoryCreate",
    "CategoryResponse",
    "CategoryUpdate",
    "TransactionCreate",
    "TransactionResponse",
    "TransactionUpdate",
    "TransactionFilter",
    "TransactionRuleCreate",
    "TransactionRuleResponse",
    "TransactionRuleUpdate",
    "CSVImportRequest",
    "CSVImportResponse",
    "SpendingByCategoryResponse",
    "SpendingTrendResponse",
    # Insight schemas
    "SpendingForecastResponse",
    "CashflowForecastResponse",
    "PredictiveInsightCreate",
    "PredictiveInsightUpdate",
    "PredictiveInsightResponse",
    "SpendingAnomalyResponse",
    "DashboardInsightsResponse",
    "GenerateForecastRequest",
    "InsightFilterParams",
]